import { NavBar } from '@/components/NavBar/NavBar'
import './globals.css'
import { ClerkProvider,SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RodoAluga',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body className={inter.className}>
        <SignedIn>
          <NavBar/>
        {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
        </body>
      </ClerkProvider>
    </html>
  )
}
